[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/docker/cli"
  version = "v18.06.0-ce"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.0.0-rc.8"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
