[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/docker/cli"
  version = "v18.06.0-ce"

[[constraint]]
  name = "github.com/docker/distribution"
  branch = "master"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.0.0-rc.8"

[[constraint]]
  name = "github.com/xeipuuv/gojsonschema"
  version = "v1.1.0"

# We are using this because it unmarshals yaml to map[string]interface{} which
# works better with json schema validation.
[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "v1.0.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
